---
title: ""
---


## Contact Information

- 7-3-1 Hongo, Bunkyo-ku, Japan, Institute of Social Science, the University of Tokyo

- Email: keisukekawata[at]iss.u-tokyo.ac.jp (please replace [at] with @)

## Education

- B.A. in Economics, Kansai University, March 2007

- M.A. in Economics, Osaka University, March 2009

- Ph.d. in Economics, Osaka University, March 2012

## Positions

- Associate professor, Institute of Social Sciece, University of Tokyo, April 2017 - current

- Associate professor, Graduate School for International Development and Cooperation , Hiroshima
University, October 2013 - March 2017

- Assistant professor, Graduate School of Social Science, Hiroshima University, September 2011-
September 2013

- Research Fellow of Japan Society for the Promotion of Science April 2010-August 2011

## Referred Journal

- Sumida, Sugata, and Keisuke Kawata. ["An analysis of the learning performance gap between urban and rural areas in sub-Saharan Africa."](https://doi.org/10.15700/saje.v41n2a1779) South African Journal of Education 41, no. 2 (2021).

- Fukai, Taiyo, Hidehiko Ichimura, Keisuke Kawata. ["Describing the impacts of COVID-19 on the labor market in Japan until June 2020."](https://doi.org/10.1007/s42973-021-00081-z) Japanese Economic Review (2021).

- Kawata, Keisuke, Yasuhiro Sato. ["A first aid kit to assess welfare impacts."](https://doi.org/10.1016/j.econlet.2021.109928) Economics Letters (2021): 109928.

- Kawaguchi, Daiji, Keisuke Kawata, and Takahiro Toriyabe. ["An assessment of Abenomics from the labor market perspective."](https://doi.org/10.1111/aepr.12343) Asian Economic Policy Review (2021).

- Vu, Ha Thu, Duc Tran, Daisaku Goto, and Keisuke Kawata. ["Does experience sharing affect farmers’ pro-environmental behavior? A randomized controlled trial in Vietnam."](https://doi.org/10.1016/j.worlddev.2020.105062) World Development 136 (2020): 105062.

- Azimy, Mohammad Wais, Ghulam Dastgir Khan, Yuichiro Yoshida, and Keisuke Kawata. ["Measuring the Impacts of Saffron Production Promotion Measures on Farmers’ Policy Acceptance Probability: A Randomized Conjoint Field Experiment in Herat Province, Afghanistan."](https://doi.org/10.3390/su12104026) Sustainability 12.10 (2020): 4026.

- Blevins, Benjamin K., and Keisuke Kawata. ["The orphan impact: HIV-AIDS and student test scores from sub-Saharan Africa."](https://doi.org/10.1080/00131911.2019.1689100) Educational Review (2019): 1-24.

- Yamamoto, Yuki, Ken’ichi Matsumoto, Keisuke Kawata, and Shinji Kaneko. ["Gender-based differences in employment opportunities and wage distribution in Nepal."](https://doi.org/10.1016/j.asieco.2019.07.004) Journal of Asian Economics 64 (2019): 101131.

- Setiawan, Rulli Pratiwi, Shinji Kaneko, and Keisuke Kawata. ["Impacts of pecuniary and non-pecuniary information on pro-environmental behavior: A household waste collection and disposal program in Surabaya city."](https://doi.org/10.1016/j.wasman.2019.04.015) Waste Management 89 (2019): 322-335.

- Sydavong, Thiptaiya, Daisaku Goto, Keisuke Kawata, Shinji Kaneko, and Masaru Ichihashi. ["Potential demand for voluntary community-based health insurance improvement in rural Lao People’s Democratic Republic: a randomized conjoint experiment."](https://doi.org/10.1371/journal.pone.0210355) PloS one 14.1 (2019): e0210355.

- Bilotkach, Volodymyr, Keisuke Kawata, Tae Seung Kim, Jaehong Park, Putut Purwandono, and Yuichiro Yoshida. ["Quantifying the impact of low-cost carriers on international air passenger movements to and from major airports in Asia."](https://doi.org/10.1016/j.ijindorg.2018.03.012) International Journal of Industrial Organization 62 (2019): 28-57.

- Fukuda, Katsufumi, Rofiq Isdwiyani, Keisuke Kawata, and Yuichiro Yoshida. ["Measuring the impact of modern waste collection and processing service attributes on residents’ acceptance of waste separation policy using a randomised conjoint field experiment in Yogyakarta Province, Indonesia."](https://doi.org/10.1177/0734242X18793939) Waste Management & Research 36.9 (2018): 841-848.

- Dastgir, Ghulam, Keisuke Kawata, and Yuichiro Yoshida. ["Effect of forced relocation on household income and consumption patterns: Evidence from the Aynak copper mine project in Afghanistan."](https://doi.org/10.1080/00220388.2017.1385767) The Journal of Development Studies 54.11 (2018): 2061-2077.

- Nwe, Khin, Keisuke Kawata, and Yuichiro Yoshida. ["Recent Political Change in Myanmar and Its Impact on her Economic Growth."](https://doi.org/10.1111/asej.12141) Asian Economic Journal 32.1 (2018): 39-54.

- Manoratna, Dinushi Anupama, Keisuke Kawata, and Yuichiro Yoshida. ["Environmental impact and travel time savings of a new monorail system in colombo’s commuting traffic."](https://doi.org/10.1016/j.trd.2016.12.003) Transportation Research Part D: Transport and Environment 51 (2017): 122-128.

- Kawata, Keisuke, Kentaro Nakajima, and Yasuhiro Sato. ["Multi-region job search with moving costs."](https://doi.org/10.1016/j.regsciurbeco.2016.10.002) Regional Science and Urban Economics 61 (2016): 114-129.

- Indarto, J., S. Kaneko, and K. Kawata. ["Do forest permits cause deforestation in Indonesia?."](https://doi.org/10.1505/146554815815500651) International Forestry Review 17.2 (2015): 165-181.

- Kawata, Keisuke. ["Work hour mismatches and on-the-job search."](https://doi.org/10.1016/j.econmod.2015.03.009) Economic Modelling 47 (2015): 280-291.

- Hizen, Yoichi, Keisuke Kawata, and Masaru Sasaki. ["An experimental test of a committee search model."](https://doi.org/10.1016/j.euroecorev.2013.03.002) European Economic Review 61 (2013): 59-76.

- Kawata, Keisuke, and Yasuhiro Sato. ["On-the-job search in urban areas."](https://doi.org/10.1016/j.regsciurbeco.2012.04.004) Regional science and urban economics 42.4 (2012): 715-726.

## Presentation in Conference

- The Asian and Australasian Society of Labour Economics, Soul National University, Dec 13-15, 2018.
Title: Information Effect and Preference for Migration Policy.
2

- The 6th Asian Political Methodology Meeting, Doshiha University, Jan 5 - 6, 2018. Title: Information
Effect and Preference for Migration Policy.

- International Association of Applied Econometrics 2017 Annual Conference, Hotel Emisa Sapporo,
June, 27, 2017, Title: Estimating Effects of Working Conditions on Labor Surplus: Application to
Rural Myanmar.

- Society for Political Methodology Summer Methods Meetings, University of Wisconsin, Madison, June,
16, 2017, Title: A Nonparametric Welfare Analysis on Water Quality Improvement of the Floating
People on Inlay Lake via a Randomized Conjoint Field Experiment

- The Applied Regional Science Conference, Ryukyu University, November, 29, 2014, Title: Foreign
influence and populism.

- The 27th Annual Conference of the European Society for Population Economics, the University if
Minho, Portugal, June 18, 2014, Title: Work Hour Mismatch and On-the-job Search.

- The Applied Regional Science Conference, Kyoto University, December, 14, 2013, Title: Protectionism
and Employment Promotion Policy: The Role of International Policy Agreements. Labor Economics
Conference, Nihon University, September 13, 2013, Title: Working out the impacts of labor market
integration.

- The 2013 meeting of the Asia-Pacific Economic Science Association, Waseda University, February,
16, 2013, Title: Committee Search with Ex-ante Heterogeneous Agents: Theory and Experimental
Evidence.

- The 26th Annual Conference of ARSC, Aomori Public College, November, 17, 2012, Title: Explicit
Spatial Friction and Workers Heterogeneity in Urban Search-Matching Models.

- Labor Economics Conference, Osaka University, September 17, 2012, Title: Globalization and Optimal
Employment Protection Policy.

- Japanese Economic Association, Hokkaido University, June 23, 2012, Title: Globalization and Optimal
Employment Protection Policy.

- Association for Public Economic Theory 12, Academia Sinica, Taiwan, June 12, 2012 Title: Changing
Worker’s States and Inefficient Decisions on Turnover.

- The Econometric Society Australasian Meeting, the University of Adelaide, Australia, July 7, 2011,
Title: Changing worker’s states and inefficient decisions on turnover.

- Japanese Economic Association, Kumamoto Gakuen University, May 21, 2011, Title: On-the-job search
in city areas.

- The 2011 meeting of the Asia-Pacific Economic Science Association, the University of Nottingham
Malaysia Campus, Malaysia, February 12, 2011 Title: An Experimental Test of a Collective Search
Model.

- International Workshop on Experimental Economics and Finance, Xiamen University, China, December
15, 2010, Title: An Experimental Test of a Collective Search Model.

- Applied Regional Science Conference, Nagoya University, December 4, 2010, Title: On-the-job Search
in a City.

- Japanese Economic Association, Kwansei Gakuin University, September 18, 2010, Title: An Experimental Test of a Collective Search Model.

- Experimental Social Science Conference, Hitotsubashi University, September 12, 2010, Title: An Experimental Test of a Collective Search Model.

- Japanese Economic Association, Chiba University, June 5, 2010, Title: Self-confidence and optimal
design of employment protection policies.


### Papers in Conference Proceedings

- "Explaining the Gender Gap in Student Performance in Mozambique:The Role of Household Tasks", (with Sugata Sumida), ICET2015 Yearbook, Pages 225-236.

- Refereed Journal in Japanese”大規模地域イベントが高速道路利用に与える効果の推定" (with Taichi Nomoto). Expressways and automobiles, Volume 60, 23-31, March 2017. (「道路と交通論文賞」受賞)

### Books in English

- Chapter 15 (with Yoichi Hizen and Masaru Sasaki) in "Behavioral Interactions, Markets, and Economic Dynamics" (Editors: Sinsuke Ikeda, H.K. Kato, Fumio Ohtake, and Y. Tsutsui) 

### Books in Japanese

- Chapter 6 & 7 (with Daiji Kawaguchi) in "解雇規制を問い直す -- 金銭解決の制度設計"（Editors: Shinya Ouchi, Daiji Kawaguchi）

- Chapter 12  in "日本の労働市場 -- 経済学者の視点"（Editors: Daiji Kawaguchi）

### Miscellaneous

- "日本の労働市場におけるミスマッチの測定" 経済分析, 199, 2019.

- "Efficiency of Skill Training for Acquiring Sector-Specific Skills with Search Frictions",  Osaka Economic Papers, Volume 61, Number 4, March 2012.

- "雇用ミスマッチの概念の整理"  (with Masaru Sasaki),  Japanese Journal of Labour Studies, Volume 54, Number 9, Page 4-14, September 2012.

- "チャイナ・シンドロームーアメリカの地域労働市場に対する輸入の影響",  Japanese Journal of Labour Studies, Volume 55, Number 4, Page 84-85, April 2013.

- [短期留学プログラムが語学力到達度に与える影響について:広島大
学 START プログラムの事例から](https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxrZWlzdWtla2F3YXRhN3xneDoxOTQwNDhhNDNkZGIwZWNm)

### Lecture

- Machine Learning for Economics (Graduate, at University of Tokyo, Autumn 2019-2020)

- Advanced Labor Economics (Undergraduate, at University of Tokyo, Spring 2018, Autumn
2019-2020)

- Econometrics (Undergraduate, at Musashi University, Spring/Autumn 2019-2020)

- Data Visualization (Graduate/Undergraduate, at Hiroshima University, Autumn 2020)

- Labor Economics (Undergraduate, at Tokyo Metropolitan University, Spring 2019)

- Money and Banking (Graduate, at Hiroshima University, Spring 2018-2019)

- Search Theory (Graduate, at University of Tokyo, Autumn 2017)

- Time Series Econometrics (Graduate, at Hiroshima University, Autumn 2017-2019)

- Development Econometrics (Graduate, at Hiroshima University, Autumn 2015)

- Econometrics (Graduate, at Hiroshima University, Spring 2014-2016)

- Economic Development and Policy (Graduate, at Hiroshima University, Spring 2014-2015)

- Labor Economics (Undergraduate, at Hiroshima University, Autumn 2011-2013)

- Labor Economics (at Hiroshima University, Autumn 2011-2013)
