---
title: "Keisuke Kawata's Website"
---

川田恵介 ([CV](https://www.dropbox.com/s/vck9aa7d460c65o/kawata.pdf?dl=0))

Associate professor, [Institute of Social Sciences](https://www.iss.u-tokyo.ac.jp/), and also [Center for Social Research and Data Archives](https://csrda.iss.u-tokyo.ac.jp/english/), [The University of Tokyo](https://www.u-tokyo.ac.jp/en/index.html) (since 2017).

**Academic area:** Economics

**Research interest:** Labor, Development, Spatial, & Empirical Economics.

**Research papers:** See [semantic scholar](https://www.semanticscholar.org/author/Keisuke-Kawata/51184440), [publon](https://publons.com/researcher/3520251/keisuke-kawata/publications/), [google scholar](https://scholar.google.com/citations?user=edeB7xsAAAAJ&hl=en&oi=ao), [researcher map](https://researchmap.jp/kawatakeisuke?lang=en), and [github](https://github.com/tetokawata)

**Lecture:**

  - Machine Learning For Economist (for graduate/undergraduate, at the University of Tokyo)

      - [Github](https://github.com/tetokawata/TargetML)
    
  - Empirical Labor Economics (for graduate, at Osaka University)

      - [Github](https://github.com/tetokawata/EmpiricalLaborEconomics)

  - Machine Learning For Economist (for undergraduate, at Musashi University)

      - [Github](https://github.com/tetokawata/UnderGradEconML)
    
  - Intensive
  
    - Data Visualization (for undergraduate, at Tokyo Keizai University)

    - Machine Learning (for working person, at the Japan Center for Economic Research)
  
    - Machine Learning/AI Boot Camp (for reseacher/working person, at the Bank of Japan)

  - 補助資料(日本語)

      - [母平均の推定: OLSと機械学習](https://tetokawata.github.io/NoteBLP/)
      
      - [格差/因果/比較分析](https://github.com/tetokawata/NoteBalance)
