---
title: ""
---

## Working Papers

- Taiyo Fukai, Keisuke Kawata, Mizuki Komura and Takahiro Toriyabe. [Gender gap in the ask salaries: evidence from larger administrative data](https://csrdadps.com/paper/93)

## Referred Journal

- Sayaka Usui, Benjamin K. Blevins and Keisuke Kawata. [Social gender inequality and the gender gap in the classroom: evidence from Southern and Eastern Africa](https://www.tandfonline.com/doi/citedby/10.1080/02589001.2024.2375658?scroll=top&needAccess=true) Journal of Contemporary African Studies (forthcoming)

- Mirlan Atabekov, Volodymyr Bilotkach, Keisuke Kawata, Ghulam Dastgir Khan, Chikage Miyoshi, Miyu Sakamoto and Yuichiro Yoshida. [Double-edged impacts of carbon footprint information on international air travel demand](https://www.sciencedirect.com/science/article/pii/S0969699724000358?casa_token=jM4-upHz3QoAAAAA:pLyOtt04K-YsQY8Nha_9-Gnh94TmohsKyCmzs6N6Jy8CAQ8J1VLeLnaxTC8slDqSg6WS2d9txg) Journal of Air Transport Management 117 (2024) : 102570.


- Keisuke Kawata, Kenneth McElwain, and Masaki Nakabayashi. ["Narrative premiums in policy persuasion"](https://onlinelibrary.wiley.com/doi/full/10.1111/pops.12928) Political Psychology 45 (2024): 383-405.

- Taiyo Fukai, Keisuke Kawata, and Masaki Nakabayashi. ["Updated beliefs and shaken confidence: evidence from vaccine hesitancy caused by experiencing “COVID arm”"](https://bmcinfectdis.biomedcentral.com/articles/10.1186/s12879-023-08558-5) BMC Infectious Diseases 23 (2023): 612.

    - [CSRDA Discussion Paper Series](https://csrdadps.com/paper/35)

- Keisuke Kawata, and Masaki Nakabayashi. ["Persistent mind: The effects of information provision on policy preferences"](https://doi.org/10.1016/j.jpolmod.2023.05.002) Journal of Policy Modeling 45 (2023): 522-537.

    - [CSRDA Discussion Paper Series](https://csrdadps.com/paper/5)

- Takashi Iida, Keisuke Kawata, and Masaki Nakabayashi. ["The citizen Preferences–Positive externality trade-off a survey study of COVID-19 vaccine deployment in Japan"](https://doi.org/10.1016/j.ssmph.2022.101191) SSM-Population Health (2022): 101191.

    - [CSRDA Discussion Paper Series](https://csrdadps.com/api/files/24/58e0c079-64e1-4388-916e-58b6e38b9f43.pdf)

- Liu, Yang, and Keisuke Kawata. ["Labour market and wage inequalities between permanent rural migrants and urban-born residents in China."](https://doi.org/10.1080/00036846.2021.1925079) Applied Economics (2022): 1-15.

- Blevins, Benjamin K., and Keisuke Kawata. ["The orphan impact: HIV-AIDS and student test scores from sub-Saharan Africa."](https://doi.org/10.1080/00131911.2019.1689100) Educational Review 73 (2021): 690-713.

- Kawata, Keisuke, and Masaki Nakabayashi. ["Determinants of COVID-19 vaccine preference: A survey study in Japan."](https://doi.org/10.1016/j.ssmph.2021.100902) SSM-Population Health 15 (2021): 100902.

  - [CSRDA Discussion Paper Series](https://csrdadps.com/paper/16)

- Sumida, Sugata, and Keisuke Kawata. ["An analysis of the learning performance gap between urban and rural areas in sub-Saharan Africa."](https://doi.org/10.15700/saje.v41n2a1779) South African Journal of Education 41 (2021): 1-17.

- Fukai, Taiyo, Hidehiko Ichimura, and Keisuke Kawata. ["Describing the impacts of COVID-19 on the labor market in Japan until June 2020."](https://doi.org/10.1007/s42973-021-00081-z) Japanese Economic Review 72 (2021): 439-470.

  - [CSRDA Discussion Paper Series](https://csrdadps.com/paper/15)

- Kawata, Keisuke, and Yasuhiro Sato. ["A first aid kit to assess welfare impacts."](https://doi.org/10.1016/j.econlet.2021.109928) Economics Letters (2021): 109928.

  - [CIRJE Discussion Paper Series](http://www.cirje.e.u-tokyo.ac.jp/research/dp/2021/2021cf1163.pdf)
  
    - [Non technical introduction (Japanese)](http://www.crepe.e.u-tokyo.ac.jp/material/crepecl12.html)

- Kawaguchi, Daiji, Keisuke Kawata, and Takahiro Toriyabe. ["An assessment of Abenomics from the labor market perspective."](https://doi.org/10.1111/aepr.12343) Asian Economic Policy Review 16 (2021): 247–278.

- Vu, Ha Thu, Duc Tran, Daisaku Goto, and Keisuke Kawata. ["Does experience sharing affect farmers’ pro-environmental behavior? A randomized controlled trial in Vietnam."](https://doi.org/10.1016/j.worlddev.2020.105062) World Development 136 (2020): 105062.

- Azimy, Mohammad Wais, Ghulam Dastgir Khan, Yuichiro Yoshida, and Keisuke Kawata. ["Measuring the Impacts of Saffron Production Promotion Measures on Farmers’ Policy Acceptance Probability: A Randomized Conjoint Field Experiment in Herat Province, Afghanistan."](https://doi.org/10.3390/su12104026) Sustainability 12.10 (2020): 4026.

- Yamamoto, Yuki, Ken’ichi Matsumoto, Keisuke Kawata, and Shinji Kaneko. ["Gender-based differences in employment opportunities and wage distribution in Nepal."](https://doi.org/10.1016/j.asieco.2019.07.004) Journal of Asian Economics 64 (2019): 101131.

- Setiawan, Rulli Pratiwi, Shinji Kaneko, and Keisuke Kawata. ["Impacts of pecuniary and non-pecuniary information on pro-environmental behavior: A household waste collection and disposal program in Surabaya city."](https://doi.org/10.1016/j.wasman.2019.04.015) Waste Management 89 (2019): 322-335.

- Sydavong, Thiptaiya, Daisaku Goto, Keisuke Kawata, Shinji Kaneko, and Masaru Ichihashi. ["Potential demand for voluntary community-based health insurance improvement in rural Lao People’s Democratic Republic: a randomized conjoint experiment."](https://doi.org/10.1371/journal.pone.0210355) PloS one 14.1 (2019): e0210355.

- Bilotkach, Volodymyr, Keisuke Kawata, Tae Seung Kim, Jaehong Park, Putut Purwandono, and Yuichiro Yoshida. ["Quantifying the impact of low-cost carriers on international air passenger movements to and from major airports in Asia."](https://doi.org/10.1016/j.ijindorg.2018.03.012) International Journal of Industrial Organization 62 (2019): 28-57.

- Fukuda, Katsufumi, Rofiq Isdwiyani, Keisuke Kawata, and Yuichiro Yoshida. ["Measuring the impact of modern waste collection and processing service attributes on residents’ acceptance of waste separation policy using a randomised conjoint field experiment in Yogyakarta Province, Indonesia."](https://doi.org/10.1177/0734242X18793939) Waste Management & Research 36.9 (2018): 841-848.

- Dastgir, Ghulam, Keisuke Kawata, and Yuichiro Yoshida. ["Effect of forced relocation on household income and consumption patterns: Evidence from the Aynak copper mine project in Afghanistan."](https://doi.org/10.1080/00220388.2017.1385767) The Journal of Development Studies 54.11 (2018): 2061-2077.

- Nwe, Khin, Keisuke Kawata, and Yuichiro Yoshida. ["Recent Political Change in Myanmar and Its Impact on her Economic Growth."](https://doi.org/10.1111/asej.12141) Asian Economic Journal 32.1 (2018): 39-54.

- Manoratna, Dinushi Anupama, Keisuke Kawata, and Yuichiro Yoshida. ["Environmental impact and travel time savings of a new monorail system in colombo’s commuting traffic."](https://doi.org/10.1016/j.trd.2016.12.003) Transportation Research Part D: Transport and Environment 51 (2017): 122-128.

- Kawata, Keisuke, Kentaro Nakajima, and Yasuhiro Sato. ["Multi-region job search with moving costs."](https://doi.org/10.1016/j.regsciurbeco.2016.10.002) Regional Science and Urban Economics 61 (2016): 114-129.

- Indarto, J., S. Kaneko, and K. Kawata. ["Do forest permits cause deforestation in Indonesia?."](https://doi.org/10.1505/146554815815500651) International Forestry Review 17.2 (2015): 165-181.

- Kawata, Keisuke. ["Work hour mismatches and on-the-job search."](https://doi.org/10.1016/j.econmod.2015.03.009) Economic Modelling 47 (2015): 280-291.

- Hizen, Yoichi, Keisuke Kawata, and Masaru Sasaki. ["An experimental test of a committee search model."](https://doi.org/10.1016/j.euroecorev.2013.03.002) European Economic Review 61 (2013): 59-76.

- Kawata, Keisuke, and Yasuhiro Sato. ["On-the-job search in urban areas."](https://doi.org/10.1016/j.regsciurbeco.2012.04.004) Regional science and urban economics 42.4 (2012): 715-726.

## Others

- [労働者の就業選好: 就業支援NPOとの共同調査結果 (工藤, 吉岡, 龍治)](https://www.dropbox.com/s/63gzawwisrxo11a/DraftPDF.pdf?dl=0)
