---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The 19th Applied Econometrics Conference

- 第１９回応用計量経済学カンファレンス

    - Conference for early carrer empirical economists.

**Date:** November 9, 2024 (Saturday)

**Schedule:**

- 10:30~10:35 Opening remark

- 10:35 ~ 11:20

    - Speaker: 則友雄磨 (Cornell University), Discutant: 田中隆一 (東京大学)
    
    - Title: Does the Timing of Productivity Shocks in Childhood Affect Educational Attainment?

- 11:20 ~ 12:05

    - Speaker: 近藤卓司 (University of California, Davis), Discutant: 笹原彰 (慶應大学)
    
    - Title: Trade Shock and Intergenerational Income Mobility.

- 12:05 ~ 13:05: Breaks

- 13:05 ~ 13:50

    - Speaker: Fei Gao (早稲田大学), Discutant: 淺井顕太郎 (京都大学)
    
    - Title: How Do Gamblers React to Wins? Evidence from Bank Transaction Data in Japan.

- 13:50 ~ 14:35

    - Speaker: 西畑壮哉 (慶應大学), Discutant: 室岡健志 (大阪大学) 
    
    - Title: Pressure, Reference Point, and Risk-taking Behavior: Evidence of Bench Press Competition.

- 14:35 ~ 14:50: Breaks 

第2セッション 座長 野口晴子 (早稲田大学)

- 14:50 ~ 15:35

    - Speaker: 小谷厚起 (東京大学), Discutant: 後藤潤(政策研究大学院大学)
    
    - Title: Connecting to Electricity: Technical Change and Regional Development.

- 15:35 ~ 16:20

    - Speaker: 池内里桜(大阪大学), Discutant: 福元真 (早稲田大学)
    
    - Title: #MeToo and Beyond: Addressing Gender Inequality in the Workplace.

- 16:20 ~ 16:35: Breaks

- 16:35 ~ 17:20

    - Speaker: 守屋隆弘 (Stony Brook University), Discutant: 中林惇 (京都大学)
    
    - Title: Communication Technology Advance and Consequences: Using Two-sided Search Model.

- 18:00 ~ 20:00: Reception

**Session:** In-Person (online available for those living abroad)

**Venue:** Kojima Conference Room, Hongou Campus, University of Tokyo

- **Applicants:** Graduate students, post-doctoral researchers, and other researchers on fixed-term contracts. (Domestic travel and accommodation expenses for in-person participants will be covered).

**Secretariat:** For inquiries regarding planning and content, please contact (Keisuke Kawata: keisukekawata@iss.u-tokyo.ac.jp)

**Supports:**

本コンファレンスの開催にあたっては次の組織・研究資金の援助を受けています。

- 東京大学日本経済国際共同研究センター

- 国際共同研究加速基金(国際先導研究)「パンデミック後日本とアジアの持続的社会経済復興のための戦略的国際研究アライアンス（研究代表者：澤田康幸）」

- TCER若手育成支援事業

**Organizing Committee:** 臼井恵美子、川ロ大司、川田恵介、佐々木勝、中林純、西脇雅人、野口晴子
